name: Rebuild Container and Deploy to ECS
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - "terraform/**"
      - ".github/workflows/backend-deploy.yaml"

env:
  AWS_REGION: ${{ vars.AWS_REGION || 'us-east-1' }}

jobs:
  build-and-push:
    environment: dev
    env:
      ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
      ECS_CLUSTER: ${{ vars.ECS_CLUSTER }}
      ECS_SERVICE: ${{ vars.ECS_SERVICE }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_OIDC_ROLE }}

      - name: Login to ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Run embeddings script
        working-directory: backend
        run: |
          export CHAT_MODEL__TYPE=${{ vars.CHAT_MODEL__TYPE }}
          export CHAT_MODEL__API_KEY=${{ secrets.CHAT_MODEL__API_KEY }}
          uv sync
          uv run python scripts/embed_stac.py

      - name: Build and push image (SHA tag)
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.ecr.outputs.registry }}
          RUN_ATTEMPT: ${{ github.run_attempt }}
        run: |
          SHORT_SHA="sha-${GITHUB_SHA::7}"
          IMAGE="$ECR_REGISTRY/${{ env.ECR_REPOSITORY }}"
          TAG="$IMAGE:$SHORT_SHA-$RUN_ATTEMPT"

          echo "Building and pushing image: $TAG"

          docker build -t "$TAG" --platform linux/amd64 --target prod -f backend/Dockerfile backend
          docker push "$TAG"

          docker tag "$TAG" "$IMAGE:latest"
          docker push "$IMAGE:latest"
          echo "Pushed: $IMAGE:latest"

      - name: Deployment to ECS
        run: |
          aws ecs update-service --cluster ${{ env.ECS_CLUSTER }} --service ${{ env.ECS_SERVICE }} --force-new-deployment > /dev/null

      - name: Wait for Service to Stabilize
        run: |
          aws ecs wait services-stable --cluster ${{ env.ECS_CLUSTER }} --services ${{ env.ECS_SERVICE }} > /dev/null
