name: Build and push backend docker image 

on:
  push:
    branches: [ "build/add-ecr-workflow"]
    paths:
      - 'backend/**'
      - 'terraform/**'
      - '.github/workflows/backend-deploy.yaml'

env:
  AWS_REGION: ${{ vars.AWS_REGION || 'us-east-1' }}

jobs:
  build-and-push:
    environment: dev
    env:
      ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
      ECS_CLUSTER: ${{ vars.ECS_CLUSTER }}
      ECS_SERVICE: ${{ vars.ECS_SERVICE }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_OIDC_ROLE }}

      - name: Login to ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Install uv based on the config files in the working-directory
        uses: astral-sh/setup-uv@v7

      - name: Run embeddings script
        working-directory: backend
        run: |
          export MISTRAL_API_KEY=${{ secrets.TF_VAR_MISTRAL_API_KEY }}
          export JWT_KEY=${{ secrets.TF_VAR_JWT_KEY }}
          uv sync
          uv run python scripts/embed_stac.py

      - name: Build and push image (SHA tag)
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.ecr.outputs.registry }}
        run: |
          SHORT_SHA="sha-${GITHUB_SHA::7}"
          IMAGE="$ECR_REGISTRY/${{ env.ECR_REPOSITORY }}"
          echo "Building and pushing $IMAGE:$SHORT_SHA"

          docker build -t "$IMAGE:$SHORT_SHA" --platform linux/amd64 --target prod -f backend/Dockerfile backend
          docker push "$IMAGE:$SHORT_SHA"
          
          echo "Pushed: $IMAGE:$SHORT_SHA"
          
          if [ "${{ github.ref }}" = "refs/heads/build/add-ecr-workflow" ]; then
            echo "Tagging $IMAGE:$SHORT_SHA as :latest"
            docker tag "$IMAGE:$SHORT_SHA" "$IMAGE:latest"
            docker push "$IMAGE:latest"
            echo "Pushed: $IMAGE:latest"
          fi

      - name: Deployment to ECS
        run: |
          aws ecs update-service --cluster ${{ env.ECS_CLUSTER }} --service ${{ env.ECS_SERVICE }} --force-new-deployment > /dev/null
            
      - name: Wait for Service to Stabilize
        run: |
          aws ecs wait services-stable --cluster ${{ env.ECS_CLUSTER }} --services ${{ env.ECS_SERVICE }} --cli-connect-timeout 90 > /dev/null
